### PR TITLE
Minor functional fixes.

### PR DESCRIPTION
**Pull request by jmirabel**
I needed those changes in order to get SoT working on my computer.

### CODE REVIEW

**Review by nim65s — APPROVED** [review]

**Comment by nim65s** [comment]
Before doing that, what didn't work ? Did you had a specific error message ?

**Comment by jmirabel** [comment]
My setting is specific.
For the CMake stuff, I compiled everything from source, taking eigenpy from robotpkg. gcc complains that it cannot find eigenpy headers.

For the Python stuff, `from dynamic_graph.sot.core import Flags` (found in several places in sot-core python files) reports that it cannot find `Flags`. This error makes sense because, at the moment, it is only `dynamic_graph.sot.core.wrap.Flags`.

**Comment by nim65s** [comment]
I did add those `from dynamic_graph.sot.core import Flags`, and so far they have been working for me. Now that you mention it, I don't understand why that worked…

**Comment by nim65s** [comment]
Arg, I should have test before merge. @jmirabel : did you test in python 2 ?
Because in python 3, I have: 
```
    from wrap import Flags
ModuleNotFoundError: No module named 'wrap'
```

I'll try with `from .wrap import Flags`.

**Comment by jmirabel** [comment]
Yes, I used Python 2 (inside ROS stuff, so no other choices).

**Pull request merged**
