### PR TITLE
Bugfix (FeaturePose) + initialization check (IntegratorEuler)

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
Fixes #116

**Comment by jmirabel** [comment]
Can this be merged ?

**Comment by jmirabel** [comment]
Please, wait. I introduced a compilation while solving the conflicts due to reformatting.

**Comment by jmirabel** [comment]
It should be fine now.

**Comment by nim65s** [comment]
As CI is down, I'll test it locally.

**Comment by nim65s** [comment]
Tests are passing for me if we add #117

**Pull request merged**
