### PR TITLE
Fix Task::computeTaskExponentialDecrease when using derivative.

### LINKED ISSUE #41: Tasks with position and velocity as reference
I might have missed something but, from my understanding of class Task, the minus in this line should be a plus.

https://github.com/stack-of-tasks/sot-core/blob/b495bddb35479b66c099948fbee9b81f4e5c262b/src/task/task.cpp#L268

Let's say, `e` is the error, `I` the input, `Iref` the reference, `e_d`, `I_d`, `Iref_d` their respective time derivative, and `I_d = I_q * q_d` where `I_q` is the jacobian of the input. Then:
`e = I - Iref`
`e_d = I_q * q_d - Iref_d = - Gain * e`
So:
`I_q * q_d = - Gain * e + Iref_d`

In the code above, errorRef is equal to `- Gain * e`.

The tests I did tend to validate my reasoning but I may misuse something.

### PR DESCRIPTION
**Pull request by jmirabel**
It fixes #41.

### CODE REVIEW

**Comment by olivier-stasse** [comment]
Dear @proyan  could check with @nmansard that this is not I_ref - I ?
We have been using this for several applications without any problem.
Modifying this will have a profound impact in porting our applications codes to Pyrene.
I am very doubtful this was wrong.

**Comment by jmirabel** [comment]
With @florent-lamiraux , we could not find any code that were using `Task` and doing velocity control with position and velocity reference (i.e. with the boolean `withDerivative` set to true). There is no problem when it is set to false.

But yes, I may have missed something.

**Comment by proyan** [comment]
I looked as well and the tutorials and the unit tests that we have (mostly in sot-dynamic and sot-pattern-generator) use only position reference.

**Comment by olivier-stasse** [comment]
Ok thanks I will checked more carefully, but when making the robot walk it is suppose to follow the CoM in position and in velocity as well as for the feet position. That was done for the SoT in v2, but we have yet to port it on v3.

**Comment by jmirabel** [comment]
If the code doing COM position and velocity following is available online, could you give me a link ?

**Comment by jmirabel** [comment]
After digging a bit more, commit 3481e42752e2d11771d81d77e6eadfe48cb1f591 does the exact opposite of this change...

The commit message says:
image

If we stick to that, then, the bug is that `errorTimeDerivativeSOUT` returns the derivative with the wrong sign. The bug fix would be here instead: https://github.com/stack-of-tasks/sot-core/blob/a0067f67af8710334ff3069a7a77f400ef3f8151/src/feature/feature-abstract.cpp#L129

**Comment by jmirabel** [comment]
I checked in [stack-of-tasks/sot-pattern-generator](https://github.com/stack-of-tasks/sot-pattern-generator) and I couldn't find any occurrence of `setWithDerivative`, which, to my understanding, is mandatory to use velocity reference.

**Pull request merged**
