### PR TITLE
Add Sot::maxControlIncrementSquaredNorm + fix rank computation.

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by nim65s** [comment]
discarded ? Isn't this a bit brutal ? Shouldn't we cap it instead ?

**Comment by jmirabel** [comment]
> Shouldn't we cap it instead ?

cap ?

**Comment by jmirabel** [comment]
> Shouldn't we cap it instead ?

cap ?

**Comment by jmirabel** [comment]
> Shouldn't we cap it instead ?

cap ?

**Comment by nim65s** [comment]
with usual number types:
`control += copysign(min(threshold, fabs(tmpControl)), tmpControl)`

**Comment by jmirabel** [comment]
I implemented this as a security so the robot does not go crazy if something bad happens. If this security is triggered, it probably means that there was an error when evaluation the task. So discarding it is meaningful. What is questionable is:
- whether the saturation you propose makes sense in other scenarios,
- whether we should rely on SoT returning a good behavior.

Maybe we should add a signal called when such an error occurs. Then, it is left to the user to do something with this error.

**Comment by nim65s** [comment]
Ok, if this is intended to be a security feature, I totally understand it.

The saturation is not useful, then. And a signal for the user is a good idea.

Still, I think you should describe that this `maxControlIncrementSquaredNorm` is a security threshold in its docstring and in the DYNAMIC_GRAPH_ENTITY_ERROR :)

**Comment by nim65s** [comment]
Also, the [CI](https://gepgitlab.laas.fr/gsaurel/sot-core/-/jobs/65037)  shows a type issue:
```
In file included from …/include/sot/core/robot-utils.hh:16:0,
from …/src/tools/robot-utils.cpp:13:
…/src/tools/robot-utils.cpp: In member function 'bool dynamicgraph::sot::RobotUtil::joints_urdf_to_sot(dynamicgraph::sot::ConstRefVector, dynamicgraph::sot::RefVector)':
…/src/tools/robot-utils.cpp:219:5: error: no matching function for call to 'dynamicgraph::sot::RobotUtil::sendMsg(const char [33], dynamicgraph::MsgType, const char [118], int)'
SEND_MSG("set_urdf_to_sot should be called", MSG_TYPE_ERROR);
```

**Comment by jmirabel** [comment]
> Also, the CI shows a type issue:

Is it using the devel branch of dynamic-graph ?

**Comment by jmirabel** [comment]
It needs the 3.8.2 and it has the 3.8.1

**Comment by nim65s** [comment]
Hum… Dynamic Graph has a release which is not in robotpkg ? And master is still on 3.8.1 ? 
And  I can't find any related tarball.

Interesting.

**Comment by jmirabel** [comment]
> Hum… Dynamic Graph has a release which is not in robotpkg ? And master is still on 3.8.1 ?
> And I can't find any related tarball. And the package.xml was not updated.
> 
> Interesting.

Is this solved ?

**Comment by jmirabel** [comment]
> Still, I think you should describe that this `maxControlIncrementSquaredNorm` is a security threshold in its docstring and in the DYNAMIC_GRAPH_ENTITY_ERROR :)

I will update the documentation.

**Comment by nim65s** [comment]
It is solved, on the release branches.

**Comment by jmirabel** [comment]
> And a signal for the user is a good idea.

Any idea for the name ?

**Comment by nim65s** [comment]
"control increment danger" ? "security margin exceeded" ?

**Comment by jmirabel** [comment]
@nim65s do you mind if we merge this as is ? Noelie will need this.

**Comment by jmirabel** [comment]
@NoelieRamuzat I integrated your changes here.

**Comment by olivier-stasse** [comment]
Thanks for the improvments.

**Pull request merged**
