### PR TITLE
Fix Timer class

### PR DESCRIPTION
**Pull request by jmirabel**
- Use `clock` instead of `gettimeofday` in order to measure process time.
- Change entity names so that they are accessible in Python.

### CODE REVIEW

**Comment by jmirabel** [comment]
I update the timer to have access to time measured by `clock` and by `gettimeofday`.

**Comment by olivier-stasse** [comment]
Sorry Joseph why did you close the pull request ? I thought we should merge it...

**Comment by jmirabel** [comment]
It is to be merged soon but it is not ready yet. I pushed to github by reflex and forgot it would update this pull-request. I closed it only to mean "Don't merge it, it isn't ready".

**Comment by olivier-stasse** [comment]
I will be waiting for your confirmation.

**Comment by jmirabel** [comment]
This is now ready. I tested on my computer and it runs about 3-4 times faster.

**Comment by olivier-stasse** [comment]
3-4 times faster ! Cool \o/

**Pull request merged**
