### PR TITLE
[operator] Add HomogeneousMatrixToSE3Vector & SE3VectorToHomogeneousMatrix

### PR DESCRIPTION
**Pull request by NoelieRamuzat**
Allows to convert a vector of size 12 (which represents an Homogeneous Matrix) to a 'real' Homogeneous Matrix (dg type).
And the opposite.
Add comparison test in test_operator.cpp.

@nim65s I don't know if you already rewrite the master & devel history; if so what should I do ?
A `git rebase -i v4.10.0` first ?

### CODE REVIEW

**Comment by jmirabel** [comment]
May I ask where you need this ?

Although this may be useful is certain particular circumstances, this can generally be avoided in favor of another solution.

**Comment by NoelieRamuzat** [comment]
I need this conversion to use some signals from the PG and the SoT in sot-torque-control and TSID.
Indeed, in TSID the tasks are using vectors as references (size 3 for the CoM and 12 for the feet for instance).
TSID is not using the dynamic-graph matrix types, so I have to convert my signals to plug them.

**Comment by jmirabel** [comment]
Can you point me to the code that bridges SoT and TSID please.

**Comment by nim65s** [comment]
Hi @NoelieRamuzat,

I rewrote the history. Could you check that the commit  a8be0231b530282f6b1e8263296b02ebd39fbee9 is what you want to do in this PR ?
If so, you can use `git reset --hard a8be0231b530282f6b1e8263296b02ebd39fbee9 && git push -f origin devel` (if `origin` is your remote for your fork)

**Comment by jmirabel** [comment]
After a private discussion with @NoelieRamuzat, one of the particular case has been reached indeed.

**Comment by NoelieRamuzat** [comment]
Hi @nim65s ! 
Yes this commit is what I need in my PR thanks :)
I did the command on my fork thanks !
And thank you @jmirabel for the discussion !

**Pull request merged**
